name: CI

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Test
        permissions:
            contents: read
            actions: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout [Pull Request]
              uses: actions/checkout@v3
              if: github.event_name == 'pull_request'
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Checkout [Main]
              uses: actions/checkout@v3
              if: github.event_name != 'pull_request'
              with:
                  fetch-depth: 0

            - name: Derive SHAs
              uses: nrwl/nx-set-shas@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              id: pnpm-install
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: |
                      ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                      node_modules/
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: pnpm install

            - name: Format
              run: pnpm nx format:check --all

            - name: Lint
              run: pnpm nx run-many --output-style=stream --skip-nx-cache -t lint

            - name: Build
              run: pnpm nx run-many --output-style=stream --skip-nx-cache -t build

            - name: Test
              run: pnpm nx run-many --output-style=stream --skip-nx-cache -t test --configuration=ci

            - name: E2E
              run: pnpm nx run-many --output-style=stream --skip-nx-cache -t e2e --configuration=ci
